var defs = module.exports = {
    all_modifiers: [''].concat(Array.from('-_~|^=+*./%!@#$&;:>?"\\<,')),
    hotkey_actions: [
        ['start-input', 'Start input mode'],
        ['start-instant', 'Start instant mode'],
        ['clear-messages', 'Clear messages'],
        ['leave-focus', 'Leave focused element'],
        ['turn-off', 'Turn off until page reload'],
        ['turn-off-page', 'Turn off on this page'],
        ['turn-off-domain', 'Turn off on this domain'],
        ['show-help', 'Show help']
    ],

    selector_actions: {
        'include': 'include selector',
        'exclude': 'exclude selector',
        'add': 'add selector and return',
        'set': 'set selector to',
    },

    match_types: {
        'contain': 'URL contains',
        'not-contain': 'URL does not contain',
        'start': 'URL starts with',
        'not-start': 'URL does not start with',
        'match': 'URL matches',
        'not-match': 'URL does not match',
        'match-regexp': 'URL matches RegExp',
        'not-match-regexp': 'URL does not match RegExp',
        'match-domain': 'Domain matches',
        'not-match-domain': 'Domain does not match',
    },

    startup_actions: {
        'turn-off': 'Turn off the script',
        'turn-on': 'Turn on the script',
        'disable-hotkey': 'Disable hotkey',
        'start-input': 'Start input mode',
        'start-instant': 'Start instant mode',
    },

    alphabet_presets: [
        ['Left hand', '123456qwertyasdfgzxcvb'],
        ['Right hand', '67890yuiopghjklvbnm'],
        ['Letters', 'abcdefghijklmnopqrstuvwxyz'],
        ['Numbers', '1234567890'],
        ['Letters+Numbers', 'abcdefghijklmnopqrstuvwxyz1234567890'],
    ],

    keymaps: {
        'russian-computer': {
            title: 'Russian computer',
            keymap: {
                'ё': '`',
                'й': 'q',
                'ц': 'w',
                'у': 'e',
                'к': 'r',
                'е': 't',
                'н': 'y',
                'г': 'u',
                'ш': 'i',
                'щ': 'o',
                'з': 'p',
                'х': '[',
                'ъ': ']',
                'ф': 'a',
                'ы': 's',
                'в': 'd',
                'а': 'f',
                'п': 'g',
                'р': 'h',
                'о': 'j',
                'л': 'k',
                'д': 'l',
                'ж': ';',
                'э': '\'',
                'я': 'z',
                'ч': 'x',
                'с': 'c',
                'м': 'v',
                'и': 'b',
                'т': 'n',
                'ь': 'm',
                'б': ',',
                'ю': '.',

                'Ё': '~',
                'Й': 'Q',
                'Ц': 'W',
                'У': 'E',
                'К': 'R',
                'Е': 'T',
                'Н': 'Y',
                'Г': 'U',
                'Ш': 'I',
                'Щ': 'O',
                'З': 'P',
                'Х': '{',
                'Ъ': '}',
                'Ф': 'A',
                'Ы': 'S',
                'В': 'D',
                'А': 'F',
                'П': 'G',
                'Р': 'H',
                'О': 'J',
                'Л': 'K',
                'Д': 'L',
                'Ж': ':',
                'Э': '"',
                'Я': 'Z',
                'Ч': 'X',
                'С': 'C',
                'М': 'V',
                'И': 'B',
                'Т': 'N',
                'Ь': 'M',
                'Б': '<',
                'Ю': '>',
                '№': '#',
            }
        },
    },
}
